name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/team-urlaubsplaner-frontend:latest
          ${{ secrets.DOCKER_USERNAME }}/team-urlaubsplaner-frontend:${{ github.sha }}
    
    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/team-urlaubsplaner-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/team-urlaubsplaner-backend:${{ github.sha }}
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Update images
          docker pull ${{ secrets.DOCKER_USERNAME }}/team-urlaubsplaner-frontend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/team-urlaubsplaner-backend:latest
          
          # Stop existing containers
          docker-compose -f docker-compose.production.yml down
          
          # Start new containers
          docker-compose -f docker-compose.production.yml up -d
          
          # Clean up old images
          docker image prune -f
